### ISSUE TITLE
Usuário pode digitar valor menor que o esperado no menu

### ISSUE THREAD

**Issue by laisbastosbg** [yarasampaaio/rainbow-match#1]
O seguinte trecho de código prevê a possibilidade do usuário entrar com um valor maior do que o esperado, porém não prevê a possibilidade de um valor menor que  1 e o programa vai encerrar sem acontecer nada

https://github.com/yarasampaaio/rainbow-match/blob/cb8f713cb55200267d316a2d3945fe9db3ea8572/Sources/RainbowMatch/main.swift#L33-L36

para consertar basta alterar para
```swift
 while estilo > 5 || estilo < 1 { 
```

que quer dizer "enquanto estilo for menor que 5 ou maior que 1"

**Comment by yarasampaaio** [comment]
Muito obrigada pela sugestão, Lais! Ajeitei lá e ficou top ❤️
