### ISSUE TITLE
Um código limpo faz muita diferença!

### ISSUE THREAD

**Issue by mill3na** [yarasampaaio/rainbow-match#2]
https://github.com/yarasampaaio/rainbow-match/blob/cb8f713cb55200267d316a2d3945fe9db3ea8572/Sources/RainbowMatch/main.swift#L43

Oi, Yara! Parabéns pelo seu código! Está muito limpo e organizado. Para continuar na linha do código limpo que você tão bem implementou, que tal separar algumas partes em pequenas funções pra você chamar ao longo do seu while? Você pode separar os estilos em funções, por exemplo. Assim, fica mais legível para quem está lendo e é mais fácil de manter. :)

**Comment by yarasampaaio** [comment]
Millena, muitooo obrigada por esse Feedback, sério! Quando fui tentar implementar aprendi bastante. Olhando agora meu código ficou muito mais organizado. ❤️❤️
