### ISSUE TITLE
Input Fail

### ISSUE THREAD

**Issue by milenaalcantara** [yarasampaaio/rainbow-match#3]
https://github.com/yarasampaaio/rainbow-match/blob/cb8f713cb55200267d316a2d3945fe9db3ea8572/Sources/RainbowMatch/main.swift#L32

- Fatal error: Unexpectedly found nil while unwrapping an Optional value

### 😵‍💫 O que está acontecendo aqui?
O que está acontecendo é que você está recebendo uma entrada através da função readline() e essa entrada pode ser um opcional, no caso de uma letra (ex: 'b'), quando você tentar converter para inteiro ou ponto flutuante o programa não consegue e então a sua variável 'estilo' recebe 'nil' e por isso o código não continua.

Estou nos testes iniciais, mas encontrei essa falha na verificação. Não é algo muito grave a priori mas deixarei aqui um trecho de código que aprendi com o mentor Yuri e acho que será válido pro seu código também ☺️

### Dica de código

```swift
func askForInt(question: String) -> Int {
      print(question)
      var finalNumber: Int?
      while finalNumber == nil || finalNumber! < 0 {
          let answerString = readLine()!
          finalNumber = Int(answerString)
          if finalNumber == nil || finalNumber! < 0 {
              print("Valor inválido, digite um número:")
          }
      }

      return finalNumber!
  }
```

Se surgir qualquer dúvida sobre o código, pode me perguntar!

Com carinho, Milena Alcântara ❤️

**Comment by yarasampaaio** [comment]
Muito obrigada, Milena! ❤️ Com toda certeza essas verificações deixa o código um pouco mais à prova de erro.
