### ISSUE TITLE
Sugestão de melhoria

### ISSUE THREAD

**Issue by yago-marques** [yarasampaaio/rainbow-match#4]
# Proposta de melhoria

## Parabéns

Primeiramente, parabéns pelo seu projeto, ficou muito top!

## O que eu acho que pode ser melhorado?

Vi que o seu menu principal está quebrando ao adicionar um tipo de valor que vc não espera, isso acontece por conta do método de verificação utilizado ao ler um número inteiro, nesse trecho:

https://github.com/yarasampaaio/rainbow-match/blob/cb8f713cb55200267d316a2d3945fe9db3ea8572/Sources/RainbowMatch/main.swift#L32

Quando vc usa o `! (force unwrapping)`, vc afirma que vai receber um tipo de valor, nesse caso, vc afirma duas coisa, quando vc faz: 

```swift
var estilo = readLine()!
```

vc está afirmando que o valor de estilo é diferente de `nil`, ou seja, não é um valor nulo
e quando vc faz:

```swift
var estilo = Int(readLine()!)!
```

vc está afirmando que o valor de estilo não vai ser nulo e vai ser do tipo `Int`, por conta disso o seu programa está quebrando quando o usuário preenche o campo com valores que não podem ser lidos como `Int`

## Como eu acho que pode ser melhorado?
Existe uma estrutura no swift chamada `if let`, com essa estrutura, vc pode fazer várias verificações no `readLine()` e analisar todos os tipos de caso
exemplo:
```swift
var estilo = Int() // estou declarando a variavel estilo como um inteiro vazio
let entrada: String?  = readLine()
// aqui estou dizendo que a constante 'entrada' pode ser uma string, mas também pode 
//ser um valor nulo, no swift, também é chamado de 'nil'

if let possivelNumero = entrada, let numero = Int(possivelNumero) {
  estilo = numero
} else {
  print("Valor inválido")
}
// nessa estrutura, estou fazendo verificações no readLine recebido
```
- no trecho `if let possivelNumero = entrada` estou verificando se o valor não é nulo
- o conector `,` serve como um `AND`, o programa só vai atribuir `numero` ao `estilo` se as duas verificações estiverem verdadeiras
- no trecho `let numero = Int(possivelNumero)` estou verificando se o valor não nulo pode ser lido como um número inteiro, caso sim, estou atribuindo na constante `numero`
- Dessa maneira, eu tenho certeza que a variável `estilo` sempre vai receber o tipo de valor que eu desejo
- Se o usuário não digitar um valor que eu espero, o programa vai cair dentro do `else` e vai printar a mensagem `"Valor inválido"`

### Dicas a parte
- Dessa maneira que eu fiz, o programa só vai rodar uma única vez, então se o usuário não digitar algo válido, o programa vai printar `"Valor inválido"` e encerrar a execução. Vc pode colocar isso dentro de um `loop` e aí vc vai ter a plena certeza de que o usuário vai ser obrigado a escrever um valor válido
exemplo: 
```swift
var numeroValido = false
repeat {
  var estilo = Int() 
  let entrada: String?  = readLine()

  if let possivelNumero = entrada, let numero = Int(possivelNumero) {
    estilo = numero
    numeroValido = true
  } else {
    print("Valor inválido")
  }
} while numeroValido = false
```

Dessa forma o programa vai repetir a leitura do `readLine()` até o usuário digitar um valor válido

- Como esse código ficou um pouco grande, sugiro colocar tudo isso dentro de uma função e sempre que quiser receber um número inteiro vc pode só chamar essa função e usar o mesmo código

**Comment by yarasampaaio** [comment]
Yago, muito obrigada pelo feedback! ✨ Consegui implementar essas verificações e ficou muito bom!
