### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by Natalialocatelli** [yarasampaaio/rainbow-match#7]
Oi Yara, tudo bem? Simplesmente amei o seu projeto, achei super útil e inovador. A minha sugestão é para a primeira parte de interação com o usuário, notei que quando ele pede para inserir o nome, ele aceita números e até mesmo continua a execução do programa sem nenhuma dado inserido. Sugiro que adicione alguma aviso para que o nome seja realmente adicionado e que seja algo válido. Além disso, na linha 33 o projeto quebra, pois aceita um caractere sem ser um número, novamente, sugiro que coloque algum aviso pedindo para inserir algo válido e repetindo a pergunta para o usuário reescrever de forma correta.

**Comment by yarasampaaio** [comment]
Olá, Natália! Muito obrigada pelo Feedback ✨. Tratei essa String no meu código como você sugeriu. ❤️
